---
# tasks file for db
- name: Show hosts env
  debug:
    msg: "This host is in {{ env }} environment"

- name: Change mongo config file
  become: true
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  tags: db-tag
  notify: restart mongod