---
# handlers file for app
  - name: reload puma  
    systemd:
      name: puma
      state: reloaded
      
  - name: restart puma
    become: yes
    systemd:
      name: puma
      state: restarted