---
- name: "Reddit App: Install mongodb"
  hosts: all
  become: true
  gather_facts: no

  tasks:
  - name: Add key
    apt_key:
     keyserver: keyserver.ubuntu.com
     id: EA312927
  - name: Add repo
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
  - name: Install mongo
    apt:
      name: mongodb-org
      update_cache: yes
  - name: Enable and run as a service
    systemd:
      name: mongod
      enabled: yes
      state: started